[package]
name = "amdgpu-fan"
version = "0.1.0"
authors = ["Fabian Thorand <f.thorand@gmail.com>"]
edition = "2018"

[dependencies]
signal-hook = "0.1.8"
toml = "0.5.1"
serde = "1.0.94"
serde_derive = "1.0.94"